### PR TITLE
56 fix login page

### LINKED ISSUE #58: Fix Login Page
## Expected Behaviour

On the login page, there are two input components: one for email, one for password.

The email-field should have a mailbox-svg on the left instead of a search glass.

The password field should have a password-svg on the left. Also the input should be hidden.

## Checklist

- [x] Find two new svg's for the input fields.
- [x] Use them instead of the current svg's for the input fields.
- [x] Hide the password input field.
- [x] Check with a regex if the entered e-mail has an acceptable format.

### PR DESCRIPTION
**Pull request by ShaQay3Q**
## Checklist

Confirm you have completed the following actions prior to submitting this PR.

- [ ] There is an existing issue report for this PR.
- [ ] I have created a feature branch.
- [ ] My changes have been committed.
- [ ] I have pushed my changes to the branch.

## Title

_Give your PR a short title summarising the patch, bug fix or feature._

## Description

_Ensure the PR description clearly describes the problem and solution and provide as much relevant information as possible._

## Issue Resolution

_Tell us which issue this PR fixes._

Closes #58

## Proposed Changes

_List your proposed changes below._

-
-
-

## New or Changed Features

_Does this PR provide new or changed features or enhancements? If so, what is included in this PR?_

-
-
-

### CODE REVIEW

File: src/components/input.tsx [hunk 1]
```diff
@@ -1,19 +1,34 @@
-import { IoIosSearch } from "react-icons/io";
-
 type Props = {
```
Comment (dnmct) [inline src/components/input.tsx]: Please use native HTML input Props instead of defining them yourself

File: src/components/input.tsx [hunk 2]
```diff
@@ -1,19 +1,34 @@
...
-  icon: JSX.Element;
-} & React.DetailedHTMLProps<
-  React.InputHTMLAttributes<HTMLInputElement>,
-  HTMLInputElement
->;
+  icon?: string;
```
Comment (dnmct) [inline src/components/input.tsx]: Icon is not a string it should be an icons from heroicons

**Review by dnmct — CHANGES_REQUESTED** [review]
Please don't use custom svgs, we already installed heroicons, so please use that

**Review by dnmct — APPROVED** [review]
